### ISSUE TITLE
the example of Generate chorale harmonization on the pretrained model

### ISSUE THREAD

**Issue by faltings** [Ghadjeres/DeepBach#20]
_I extracted pretrained model files to DeepBach/models/ and DeepBach/datasets/raw_dataset/ , then  sample code " Generate a chorale of length 100" runs well.
But, after running the example of Generate chorale harmonization with soprano extracted from midi_
python3 deepBach.py -m -p

_the terminal shows errors below_
Using TensorFlow backend.
Namespace(batch_size_train=128, dataset='', ext='', length=160, midi_file='datasets/god_save_the_queen.mid', name='deepbach', num_dense=200, num_iterations=20000, num_units_lstm=[200, 200], output_file='', overwrite=False, parallel=16, reharmonization=None, steps_per_epoch=500, timesteps=16, train=0, validation_steps=20)
model models/deepbach_0 loaded
model models/deepbach_1 loaded
model models/deepbach_2 loaded
model models/deepbach_3 loaded
Traceback (most recent call last):
  File "deepBach.py", line 847, in <module>
    main()
  File "deepBach.py", line 843, in main
    pickled_dataset=pickled_dataset)
  File "deepBach.py", line 35, in generation
    parallel_updates=True, pickled_dataset=pickled_dataset)
  File "deepBach.py", line 224, in parallel_gibbs
    seq[timesteps:-timesteps, 0] = melody
ValueError: cannot copy sequence with size 168 to array axis with dimension 160

Thanks
Joe

**Comment by Ghadjeres** [comment]
Results won't be as good as expected since DeepBach will always be using the same metadata when reharmonizing your file (C major/A minor with fermata every two bars) regardless of your input file.

For the moment, it is possible to train a model that ignores the metadata information for instance by creating a new dataset (see line 755 in deepBach.py) or to manually change the chorale_metas argument so that it matches your input file.
