### ISSUE TITLE
AssertionError when use another database

### ISSUE THREAD

**Issue by playsboy** [Ghadjeres/DeepBach#36]
Dear Professor:

I follow your introduction, and have stored mid files with the same number of voices in data folder. When I run the command: python3 deepBach.py --dataset data/ --ext dowland -t 30 --timesteps 32 -u 256 256 -d 256 -b 32 in server, it shows

Traceback (most recent call last):
  File "deepBach.py", line 183, in <module>
    main()
  File "deepBach.py", line 156, in main
    metadatas=metadatas, timesteps=timesteps)
  File "/home/DeepBach-master/DeepBach/model_manager.py", line 644, in create_models
    labels) = next(gen)
  File "/home/DeepBach-master/DeepBach/data_utils.py", line 410, in generator_from_raw_dataset
    chorale_indices) > 0, "The list of chorales for the phase '%s' must not be empty" % phase
AssertionError: The list of chorales for the phase 'train' must not be empty. 

  I print the training_size and total_size in data_utils.py, and it appears 0. I don't know where is wrong. Would you mind to tell me what should I do if it is convenient. I'm very grateful to you for your help.

**Comment by Ghadjeres** [comment]
Hi,
This is probably because your files do not contain 4 different voices:
there is a default value of 4 for the number of voices in filter_file_list which shouldn't be there...
This will be fixed tomorrow. In the meantime you can remove the if statement or change the num_voices variable in filter_file_list.
Do not forget to remove the old and empty pickle file in datasets/custom_dataset if you want it to be recomputed.
(otherwise it's an issue with the dataset path, best would be to give it as an absolute path).
