### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by 23trastos** [Ghadjeres/DeepBach#49]
Hello. I am a music composer and computer lover, however I wish my programming skill were up to the level of understanding ML and your code. First of all congratulations for the project and all your activities!

I was able to set up everything in Linux and have a working model trained for 15 epochs that produces some nice outputs (not always). 

My first question is: how many epochs should it be trained to produce similar output as the examples available in the webpage?

My second question is: is there any chance that the model could be also used to expand chorales to chorale preludes as Bach did in his Organ Chorale Preludes? I think it could be a really nice task to see if there is a Deep Learning model that could realize such task of expanding music by motive elaboration from a chorale to a more complex instrumental piece.

Thanks in advance!!

**Comment by Ghadjeres** [comment]
Hi,
Thanks a lot, I'm glad that it works. 
Since it is quite an old code, I can't remember how many epochs are needed with this implementation. But a new version will be released soon. I hope it will interest you.
Concerning the generation of chorale preludes, this is above of what DeepBach is capable to produce. As you pointed, the motivic treatment is crucial for this kind of pieces and this is in fact out of reach for current algorithms. DeepBach works well due to the characteristic writing of the four-part chorales and the relative absence of long-term structure.
I had thought working on chorale preludes at some point, but this seems quite hard: there are canons, motifs, many different "styles" (consider how different are Gott, durch deine Güte;  Herr Christ, der einge Gottes-Sohn  or O Mensch, bewein dein Sünde groß) and not much data in fact.
Best
